# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "dark" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/my-logo.png"
    alt: "Sijan Malla"

### Header
header:
  logo:
    image: "assets/img/my-logo.png"
    alt: "Sijan Malla"

### Social
social:
  - title: "Github"
    icon: "fab fa-github"
    url: "https://github.com/season101"

  - title: "Github"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/sijanmalla/"

### Footer
footer:
  developer: "Developed by <strong>Sijan Malla</strong>"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "Web Design"
      slug: "web-design"

    - name: "Cloud"
      slug: "cloud"

    - name: "Data Science & AI/ML"
      slug: "ds-ai-ml"

    - name: "Software Development"
      slug: "software-development"
