name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install Jekyll and Bundler
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build
        echo "Jekyll Site Built Successfully..."

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Specify the local directory you want to sync with S3
      # In this case, it syncs the "_site" directory generated by Jekyll
      # Adjust this path if your Jekyll output directory is different
      run: |
        echo "Syncing Jekyll site to S3..."
        aws s3 sync _site/ s3://$AWS_S3_BUCKET
